### ISSUE TITLE
Removed list via app is not removed in HA

### ISSUE THREAD

**Issue by agmorpheus** [kevdliu/hacs-anylist#10]
First of all: thanks for this great integration

I have deleted a list via the Anylist app. But this list is still available in HA. I can not delete it from there. I only can deactivate the List in HA.

**Comment by kevdliu** [comment]
Can you try restarting home assistant? After restarting the delete button should be available. I'm not sure why but simply reloading the integration does not refresh the list of lists. I'll have to look into that one.

**Comment by agmorpheus** [comment]
I tried a restart but the delete button is still grayed out.

**Comment by kevdliu** [comment]
If you go to http://<your anylist addon server ip>:<port>/lists in your browser, do you see the deleted list in the output?

**Comment by agmorpheus** [comment]
The deleted list is not returned via the endpoint. 
But I found the problem. I have deactived the list in HA and then deleted it. After activating the list and restarting HA I could delete it in HA.
