### ISSUE TITLE
Please add info to install/config instructions

### ISSUE THREAD

**Issue by rouxdoo** [kevdliu/hacs-anylist#11]
I tried and failed because it wasn't spelled out in the docs - the final step after doing everything in the install/config docs it to "go to the integrations page, search for AnyList and install the integration". I was ready to uninstall as a failed project but did one last google search which turned up the solution.

Spell it out for us idiots please :)

Thanks for what you've done and I appreciate your efforts.

**Comment by kevdliu** [comment]
Thanks for the suggestion! I've updated the the instructions with how to add the integration to home assistant.
