### ISSUE TITLE
NFC Tag

### ISSUE THREAD

**Issue by stoupaspan** [kevdliu/hacs-anylist#12]
I am trying to add the following automation: when a NFC tag is scanned, then a specific item (eg Coca Cola) in a specific list (eg Supermarket) becomes unchecked. I have installed both the add-on and the integration and I am using the following code in Automations, but it doesn't work:

alias: Tag test is scanned
description: ""
triggers:
  - trigger: tag
    tag_id: 00393a3d-b5a4-489e-bbdf-d4de645e34ea
conditions: []
actions:
  - action: anylist.uncheck_item
    metadata: {}
    data:
      name: Coca Cola
      list: Supermarket
mode: single

**Comment by kevdliu** [comment]
Do you see any errors regarding anylist in the logs? Another thing you can try is go to Developer Tools -> Actions and run the anylist.uncheck_item action manually. The response code will then be displayed in the response section of the page.

**Comment by stoupaspan** [comment]
When I do that, I get a 404 code

**Comment by kevdliu** [comment]
404 means either the list is not found or the item is not found in the list. If you run
```
action: anylist.get_items
data:
  list: Supermarket
```
do you see your item listed in the response?

**Comment by stoupaspan** [comment]
Unfortunately, no! I am getting
code: 404
items: []

**Comment by kevdliu** [comment]
ok that means the list itself is not found. Go to `http://<your anylist addon ip>:<your anylsit addon port>/lists` in your browser and it'll print out all the lists in your account. Do you see your list called Supermarket in the reponse?

**Comment by stoupaspan** [comment]
Ok... I just figured out what was wrong... I am using Cloudflare with a
custom url. So when I changed the url to
http://http://homeassistant.local:<port>
it fetched the list and the NFC tag started working!!!

You are great!! Thank you very much for the help!
