### ISSUE TITLE
Support for new Todo lists

### ISSUE THREAD

**Issue by emericklaw** [kevdliu/hacs-anylist#3]
With the recent addition of Todo lists in Home Assistant I stumbled upon this repository in my search to integrate AnyList.

https://www.home-assistant.io/integrations/todo

Do you have any plans to support this in this addon?

Thanks

**Comment by kevdliu** [comment]
That's awesome that they added support for todo lists. I'll definitely look into implementing this when I get a chance.

**Comment by kevdliu** [comment]
Just added this in v1.2. Let me know how it works for you!

**Comment by Daneish** [comment]
Thanks very much for adding the Todo feature! It took me a little bit of fiddling around as initially only the update for the Add On appeared (not the HACS integration) but once I updated both, it was smooth sailing.

Thanks again for creating this integration, I love it!

**Comment by kevdliu** [comment]
Very happy to hear that, I'm glad it's working well!
