### ISSUE TITLE
HA entity doesn't match what's in Anylist app or service call

### ISSUE THREAD

**Issue by dinki** [kevdliu/hacs-anylist#8]
Hi again.  Thanks for your work on this integration.  I'm working on a project called View Assist which replicates some of the Alexa Show displays.  One of the things I'm working on is adding and removing items from the shopping list with voice.  I am noticing an oddity when it comes to the HA entity.  See here:

![image](https://github.com/kevdliu/hacs-anylist/assets/2521542/b31fad94-27bb-452c-80c1-03ac92a20b6e)

This shows the todo.anylist_alexa_shopping_list.  The unchecked_items is missing two items that I added via voice.  I can see those by running a service to grab the values from the list:

![image](https://github.com/kevdliu/hacs-anylist/assets/2521542/7d1cc34a-2040-4d33-b293-999bacbc71fb)

You can see the test items I put are here and they also show up in the Anylist app on my phone but they do not show up in the entity.

A restart of HA will refresh the list and make those items visible.  Can you tell me what I might be doing wrong?  Do I need to force a refresh somehow?

**Comment by kevdliu** [comment]
Thanks for the bug report. For testing, does the entity attribute refresh if you add/remove an item using `todo.add_item` or `todo.remove_item`? Currently the entity should refresh every 30 minutes, but I can make that configurable and also add a service call to refresh it on demand.

**Comment by dinki** [comment]
@kevdliu  I did try with both the todo.add/remove service as well as the anylist.add/remove and neither showed the updated list in the device entity attributes in dev tools but it's obvious they are there when I go to the list itself.

Adding a manual service to update would be great.  I can call it after I add/remove something to get faster results.  What you say about 30 minute update now makes sense as I'm guessing that it will also update on start up and that's why I restart was providing the updated list.

I'm super excited to use this on my tablet device with View Assist and thank you again for your continued work on this project.

**Comment by kevdliu** [comment]
You're welcome! Congrats on View Assist winning the voice assistant contest! I just tried to repro the bug on my end and the entity attribute is updating immediately after calling `todo.add_item` or `todo.remove_item`. Can you check whether the entity's state (the one that shows the number of items on the list) refreshes when you add or remove an item?

**Comment by kevdliu** [comment]
I might need to manually refresh the entity on changes just in case home assistant doesn't do it for me

**Comment by dinki** [comment]
```
service: todo.add_item
target:
  entity_id: todo.anylist_alexa_shopping_list
data:
  item: junk
  ```
  
  I issued this and it appears successful.  Looking at the list in dev tools -> states the list does not show the added item and the state number does not increase.  It does not appear in the list when I look at the 'To-do list' section of the webui.

The item is added to my Anylist list when I check the app so it is definitely there.  I will check again in 30 mins and see if it shows up.

**Comment by dinki** [comment]
I am doing this:

* Add cheese to my shopping list.  Nothing shows up
* Add beans to my shopping list.  Cheese shows up but not beans
* Add baking soda to my shopping list.  Beans shows up but not baking soda

So it seems that it updates when another item is added but does not update current item being added.

**Comment by kevdliu** [comment]
Found a bug in the companion addon (https://github.com/kevdliu/hassio-addon-anylist) that was not awaiting on the anylist request before responding. I've released v1.7.2 of the addon/binary/docker image which should have it fixed. Let me know if it works.

**Comment by kevdliu** [comment]
With the fix in place the entity should refresh immediately after adding/remove an item.

**Comment by dinki** [comment]
Thanks for the quick response and fix.  Happy to report this is working great!
